account:
    username: bot_username
    password: bot_password

bot:
    footer: ^(Questions, comments, image suggestions? All are welcomed at /r/image_linker_bot)
    seen_len: 1000
    toomuch: |
        Message to send to people who reply-reply
    extensions:
        - jpeg
        - jpg
        - png
        - gif
        - bmp
        - avi
        - tiff
        - tif
