account:
    username: bot_username
    password: bot_password

images:
    thatsthejoke: http://i.imgur.com/Z5pWhBi.jpg
    tmyk: http://i.imgur.com/7QWop.gif

aliases:
    tmyk: themoreyouknow

bot:
    footer: ^(Questions, comments, image suggestions? All are welcomed at /r/image_linker_bot)
    seen_len: 100
