account:
    username: bot_username
    password: bot_password

bot:
    useragent: Sample bot by /u/yournamehere v0.0 at /r/botsubreddithere
    footer: ^(Questions, comments, image suggestions? All are welcomed at /r/image_linker_bot)
    seen_len: 1000
    toomuch: |
        Message to send to people who reply-reply
    cleanup_time: 900  #Clean up every 15 minutes
    extensions:
        - jpeg
        - jpg
        - png
        - gif
        - bmp
        - avi
        - tiff
        - tif
    animated_extensions:
        - gif
        - avi
    switchable_extensions:
        - jpeg
        - jpg
        - gif
        - png
    status_template: status_template.html
